site_name: Expreduce

pages:
- Home: 'index.md'
- Language reference:
    - 'String': 'builtin/string/index.md'
    - 'ToString ': 'builtin/string/tostring.md'

theme: readthedocs
theme_dir: 'material'

repo_name: 'expreduce'
repo_url: 'https://github.com/corywalker/expreduce'

extra:
  version: '0.1.0'
  palette:
    primary: 'red'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Extensions
markdown_extensions:
  #- codehilite(css_class=code)
  - codehilite(css_class=language-wl)
